// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: loan.proto
package loan

import (
	"net/http"
	"strings"

	"github.com/herryg91/cdd/grst"
	grst_errors "github.com/herryg91/cdd/grst/errors"
	"google.golang.org/grpc"

	"github.com/mcuadros/go-defaults"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials"
	"gopkg.in/validator.v2"
)

type fullMethods struct {
	LoanApi_GetMySummary  string
	LoanApi_SimulateLoan  string
	LoanApi_CreateLoan    string
	LoanApi_GetLoans      string
	LoanApi_GetLoanByCode string
}

var FullMethods = fullMethods{
	LoanApi_GetMySummary:  "/loan.LoanApi/GetMySummary",
	LoanApi_SimulateLoan:  "/loan.LoanApi/SimulateLoan",
	LoanApi_CreateLoan:    "/loan.LoanApi/CreateLoan",
	LoanApi_GetLoans:      "/loan.LoanApi/GetLoans",
	LoanApi_GetLoanByCode: "/loan.LoanApi/GetLoanByCode",
}

var NeedAuthFullMethods = []string{
	"/loan.LoanApi/GetMySummary",

	"/loan.LoanApi/CreateLoan",
	"/loan.LoanApi/GetLoans",
	"/loan.LoanApi/GetLoanByCode",
}

type AuthConfig struct {
	NeedAuth bool
	Roles    []string
}

var AuthConfigFullMethods = map[string]AuthConfig{
	"/loan.LoanApi/GetMySummary":  AuthConfig{NeedAuth: true, Roles: []string{"*"}},
	"/loan.LoanApi/SimulateLoan":  AuthConfig{NeedAuth: false, Roles: []string{"*"}},
	"/loan.LoanApi/CreateLoan":    AuthConfig{NeedAuth: true, Roles: []string{"*"}},
	"/loan.LoanApi/GetLoans":      AuthConfig{NeedAuth: true, Roles: []string{"*"}},
	"/loan.LoanApi/GetLoanByCode": AuthConfig{NeedAuth: true, Roles: []string{"*"}},
}

var NeedApiKeyFullMethods = []string{}

func ValidateRequest(req interface{}) error {
	defaults.SetDefaults(req)
	if errs := validator.Validate(req); errs != nil {
		validateError := []*grst_errors.ErrorDetail{}
		for field, err := range errs.(validator.ErrorMap) {
			errMessage := strings.Replace(err.Error(), "{field}", field, -1)
			validateError = append(validateError, &grst_errors.ErrorDetail{Code: 999, Field: field, Message: errMessage})
		}
		return grst_errors.New(http.StatusBadRequest, codes.InvalidArgument, 999, "Validation Error", validateError...)
	}

	return nil
}

/*==================== LoanApi Section ====================*/

func RegisterLoanApiGrstServer(grpcRestServer *grst.Server, hndl LoanApiServer) {

	forward_LoanApi_GetMySummary_0 = grpcRestServer.GetForwardResponseMessage()

	forward_LoanApi_SimulateLoan_0 = grpcRestServer.GetForwardResponseMessage()

	forward_LoanApi_CreateLoan_0 = grpcRestServer.GetForwardResponseMessage()

	forward_LoanApi_GetLoans_0 = grpcRestServer.GetForwardResponseMessage()

	forward_LoanApi_GetLoanByCode_0 = grpcRestServer.GetForwardResponseMessage()

	RegisterLoanApiServer(grpcRestServer.GetGrpcServer(), hndl)
	grpcRestServer.RegisterRestHandler(RegisterLoanApiHandler)
}

func NewLoanApiGrstClient(serverHost string, creds *credentials.TransportCredentials, dialOpts ...grpc.DialOption) (LoanApiClient, error) {
	opts := []grpc.DialOption{}
	opts = append(opts, grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(1024*1024*20)))
	opts = append(opts, grpc.WithMaxMsgSize(1024*1024*20))
	if creds == nil {
		opts = append(opts, grpc.WithInsecure())
	} else {
		opts = append(opts, grpc.WithTransportCredentials(*creds))
	}
	opts = append(opts, dialOpts...)
	grpcConn, err := grpc.Dial(serverHost, opts...)
	return NewLoanApiClient(grpcConn), err
}
